### ISSUE TITLE
deployed on Vercel issue 

### ISSUE THREAD

**Issue by Soliman55** [phuocleoceo/meme-generator#1]
hey, how i can use this to be deployed on Vercel

**Comment by phuocleoceo** [comment]
Of course, feel free to use it, although I'm not sure if it still works now 🤗

**Comment by Soliman55** [comment]
sadly not working , thanks :)

**Comment by phuocleoceo** [comment]
Oh what a pity, maybe there is a conflict between the react/node version of this project and the current react/node version, good luck 🥳
BTW, my deployment on vercel (https://meme-generator-phuocleoceo.vercel.app/) is still working 😂

**Comment by Soliman55** [comment]
thank you i will try my best I'm kinda first time doing this :D
